capacity: 10                                                      # The size of the in que on the server
maxFilibusters: 6                                                 # The maximum number of Filibusters the server should try to create
filibusterHome: /opt/langtech/filibuster/Synthesis/SynthesisCore  # The directory where filibuster.tcl is installed
logHome: /var/log/mtm/speech-synthesis-server                     # The Filibuster log directory
minimumMemory: 4                                                  # The minimum memory that should be available before allocating a new Filibuster
timeToLive: 30                                                    # The expected life time of a Filibuster in minutes
idleTime: 100                                                     # The idle time the server will wait before looking asking for a synthesized result in milli seconds
timeout: 900                                                      # The time a job is allowed for synthesize before a timeout is returned to the caller in seconds

server:
  applicationConnectors:
    - type: http
      port: 9090
  adminConnectors:
    - type: http
      port: 9091

  requestLog:
    appenders:
    - type: file
      currentLogFilename: /var/log/mtm/speech-synthesis-server/speech-synthesis-access.log
      threshold: INFO
      archive: true
      archivedLogFilenamePattern: /var/log/mtm/speech-synthesis-server/speech-synthesis-access-%d.log
      archivedFileCount: 5
      timeZone: CET

logging:
  level: INFO
  appenders:
    - type: file
      currentLogFilename: /var/log/mtm/speech-synthesis-server/speech-synthesis.log
      threshold: ALL
      archive: true
      archivedLogFilenamePattern: /var/log/mtm/speech-synthesis-server/speech-synthesis-%d.log
      archivedFileCount: 5
      timeZone: CET
