capacity: 10
maxFilibusters: 6
timeToLive: 30 # minutes
idleTime: 100 # milli seconds
timeout: 30 # seconds

server:
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081

logging:
  level: INFO
  appenders:
    - type: console
    - type: file
      currentLogFilename: speech-synthesis.log
      threshold: ALL
      archive: true
      archivedLogFilenamePattern: speech-synthesis-%d.log
      archivedFileCount: 5
      timeZone: UTC
